# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('184b6c04e7ebde58684868a6417c2eb7_OTI0ODQyMDEyLTA1LTIyIDA3OjMxOjU4Ljk0NjY0Ng')
  end)
end
